/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppInicioRouteImport } from './routes/_app/inicio'
import { Route as AppEditaisIndexRouteImport } from './routes/_app/editais/index'
import { Route as AppEditaisNovoRouteImport } from './routes/_app/editais/novo'
import { Route as AppEditaisIdIndexRouteImport } from './routes/_app/editais/$id/index'
import { Route as AppEditaisIdEditarRouteImport } from './routes/_app/editais/$id/editar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AppRoute,
} as any)
const AppEditaisIndexRoute = AppEditaisIndexRouteImport.update({
  id: '/editais/',
  path: '/editais/',
  getParentRoute: () => AppRoute,
} as any)
const AppEditaisNovoRoute = AppEditaisNovoRouteImport.update({
  id: '/editais/novo',
  path: '/editais/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppEditaisIdIndexRoute = AppEditaisIdIndexRouteImport.update({
  id: '/editais/$id/',
  path: '/editais/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppEditaisIdEditarRoute = AppEditaisIdEditarRouteImport.update({
  id: '/editais/$id/editar',
  path: '/editais/$id/editar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/inicio': typeof AppInicioRoute
  '/editais/novo': typeof AppEditaisNovoRoute
  '/editais/': typeof AppEditaisIndexRoute
  '/editais/$id/editar': typeof AppEditaisIdEditarRoute
  '/editais/$id/': typeof AppEditaisIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/inicio': typeof AppInicioRoute
  '/editais/novo': typeof AppEditaisNovoRoute
  '/editais': typeof AppEditaisIndexRoute
  '/editais/$id/editar': typeof AppEditaisIdEditarRoute
  '/editais/$id': typeof AppEditaisIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/inicio': typeof AppInicioRoute
  '/_app/editais/novo': typeof AppEditaisNovoRoute
  '/_app/editais/': typeof AppEditaisIndexRoute
  '/_app/editais/$id/editar': typeof AppEditaisIdEditarRoute
  '/_app/editais/$id/': typeof AppEditaisIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/inicio'
    | '/editais/novo'
    | '/editais/'
    | '/editais/$id/editar'
    | '/editais/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/inicio'
    | '/editais/novo'
    | '/editais'
    | '/editais/$id/editar'
    | '/editais/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/inicio'
    | '/_app/editais/novo'
    | '/_app/editais/'
    | '/_app/editais/$id/editar'
    | '/_app/editais/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/inicio': {
      id: '/_app/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/editais/': {
      id: '/_app/editais/'
      path: '/editais'
      fullPath: '/editais/'
      preLoaderRoute: typeof AppEditaisIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/editais/novo': {
      id: '/_app/editais/novo'
      path: '/editais/novo'
      fullPath: '/editais/novo'
      preLoaderRoute: typeof AppEditaisNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/editais/$id/': {
      id: '/_app/editais/$id/'
      path: '/editais/$id'
      fullPath: '/editais/$id/'
      preLoaderRoute: typeof AppEditaisIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/editais/$id/editar': {
      id: '/_app/editais/$id/editar'
      path: '/editais/$id/editar'
      fullPath: '/editais/$id/editar'
      preLoaderRoute: typeof AppEditaisIdEditarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInicioRoute: typeof AppInicioRoute
  AppEditaisNovoRoute: typeof AppEditaisNovoRoute
  AppEditaisIndexRoute: typeof AppEditaisIndexRoute
  AppEditaisIdEditarRoute: typeof AppEditaisIdEditarRoute
  AppEditaisIdIndexRoute: typeof AppEditaisIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInicioRoute: AppInicioRoute,
  AppEditaisNovoRoute: AppEditaisNovoRoute,
  AppEditaisIndexRoute: AppEditaisIndexRoute,
  AppEditaisIdEditarRoute: AppEditaisIdEditarRoute,
  AppEditaisIdIndexRoute: AppEditaisIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
